steps:
  # Step 1: Pull the Docker image from Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'kamaln7/klein:latest']

  # Docker Push to GCR
  - name: gcr.io/cloud-builders/docker
    args: ['push', '$_GCR_HOSTNAME/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA']

images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA'

substitutions:
  _GCR_HOSTNAME: gcr.io
  _IMAGE_NAME: klein 
  _SHORT_SHA: $SHORT_SHA 