steps:
  # Step 1: Pull the Docker image from Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'kamaln7/klein:latest']

  # Step 2: Tag the image for GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'kamaln7/klein:latest', 'gcr.io/$PROJECT_ID/klein:latest']

  # Docker Push to GCR
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/$PROJECT_ID/klein:latest']

    # Deploy to Cloud Run using the secrets
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'klein-service'  # Replace with the desired Cloud Run service name
    - '--image'
    - 'gcr.io/$PROJECT_ID/klein:latest' 
    - '--region'
    - 'us-central1'  # Replace with your desired region
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'  # Optional: remove if you want to require authentication
    - '--port'
    - '5556'
    # - '--args'
    # - 'web'

images:
  - 'gcr.io/$PROJECT_ID/klein:latest'